apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql:3306"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_PASSWORD
          value: "holaquemas"
        ports:
        - containerPort: 80
          name: wordpress
